// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_not_a_scratch = "CgkIrqKCzZoeEAIQFQ"; // <GPGSID>
        public const string achievement_grinder = "CgkIrqKCzZoeEAIQEg"; // <GPGSID>
        public const string achievement_endless_destruction = "CgkIrqKCzZoeEAIQDQ"; // <GPGSID>
        public const string achievement_a_legend_is_born = "CgkIrqKCzZoeEAIQBQ"; // <GPGSID>
        public const string achievement_stubborn = "CgkIrqKCzZoeEAIQBw"; // <GPGSID>
        public const string achievement_why_not = "CgkIrqKCzZoeEAIQFw"; // <GPGSID>
        public const string achievement_the_way_of_fire = "CgkIrqKCzZoeEAIQCg"; // <GPGSID>
        public const string achievement_heartless = "CgkIrqKCzZoeEAIQEA"; // <GPGSID>
        public const string achievement_impregnable_fortress = "CgkIrqKCzZoeEAIQDw"; // <GPGSID>
        public const string achievement_genocide = "CgkIrqKCzZoeEAIQFA"; // <GPGSID>
        public const string achievement_ruthless = "CgkIrqKCzZoeEAIQCQ"; // <GPGSID>
        public const string achievement_god_among_gods = "CgkIrqKCzZoeEAIQEw"; // <GPGSID>
        public const string achievement_the_way_of_nature = "CgkIrqKCzZoeEAIQCw"; // <GPGSID>
        public const string achievement_blitzkrieg = "CgkIrqKCzZoeEAIQBg"; // <GPGSID>
        public const string achievement_a_step_is_a_step = "CgkIrqKCzZoeEAIQBA"; // <GPGSID>
        public const string achievement_end_of_the_road = "CgkIrqKCzZoeEAIQAA"; // <GPGSID>
        public const string achievement_never_gonna_give_you_up = "CgkIrqKCzZoeEAIQEQ"; // <GPGSID>
        public const string leaderboard_best_time = "CgkIrqKCzZoeEAIQAQ"; // <GPGSID>
        public const string achievement_slaughter = "CgkIrqKCzZoeEAIQCA"; // <GPGSID>
        public const string achievement_the_way_of_water = "CgkIrqKCzZoeEAIQDA"; // <GPGSID>
        public const string achievement_speed_of_light = "CgkIrqKCzZoeEAIQDg"; // <GPGSID>
        public const string achievement_savage = "CgkIrqKCzZoeEAIQFg"; // <GPGSID>
        public const string achievement_halfway_through_hell = "CgkIrqKCzZoeEAIQAw"; // <GPGSID>

}

